package com.tfg.maceteros.service.config;

public class Constantes {

	public static final String TOKEN ="eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiJiODVmNmM3MC00OGVhLTExZWEtODkyNC0zNzNlZGUyZjA2ZTkiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiYjdiOTQxNjAtNDhlYS0xMWVhLTg5MjQtMzczZWRlMmYwNmU5IiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTgyNDczMzQ0LCJleHAiOjE2MTQwMDkzNDR9.zq83YEOlPj5JOeTaBJe2G5RXiZDzkj7EmpZTBH2Md_QTGbp7fdOO0bo5CIY5AtHI5ynX7EJuHm3SQSH8cE4W2w";
	public static final String KEYS ="agua,peso,humedad_superior,humedad_inferior,temperatura_interior,humedad_ambiental,luz_ambiental,temperatura_ambiental,co2";
	public static final String ENDPOINT ="http://138.4.92.46:8080/api/plugins/telemetry/DEVICE/";
	public static final String ENDPOINT_ATTRIBUTES ="http://138.4.92.46:8080/api/v1/";

}
